mongodb:
  url: mongodb+srv://valeriichecha:LZHMuZPZ4aFtKYRc@cluster0.reed6.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
mediasoup:
  resourceInterval: 60000
  resourceLogLevel: short
  workerPool: 2
  worker:
    rtcMinPort: 10000
    rtcMaxPort: 10100
    logLevel: warn
    logTags:
      - info
      - ice
      - dtls
      - rtp
      - srtp
      - rtcp
  router:
    mediaCodecs:
      - kind: audio
        mimeType: audio/opus
        clockRate: 48000
        channels: 2
      - kind: video
        mimeType: video/VP8
        clockRate: 90000
        parameters:
          profile-id: 2
          minptime: 10
          useinbandfect: 1
          x-google-start-bitrate: 1000
      - kind: video
        mimeType: video/VP9
        clockRate: 90000
        parameters:
          x-google-start-bitrate: 1000
      - kind: video
        mimeType: video/H264
        clockRate: 90000
        parameters:
          packetization-mode: 1
          profile-level-id: 42e01f
          level-asymmetry-allowed: 1
          x-google-start-bitrate: 1000
