mediasoup:
  resourceInterval: 60000
  resourceLogLevel: short
  workerPool: 2
  worker:
    rtcMinPort: 10000
    rtcMaxPort: 10100
    logLevel: warn
    logTags:
      - info
      - ice
      - dtls
      - rtp
      - srtp
      - rtcp
  router:
    mediaCodecs:
      - kind: audio
        mimeType: audio/opus
        clockRate: 48000
        channels: 2
      - kind: video
        mimeType: video/VP8
        clockRate: 90000
        parameters:
          x-google-start-bitrate: 1000
